### ISSUE TITLE
An error occurred (AccessDenied) when calling the GetObject operation: Access Denied

### ISSUE THREAD

**Issue by smajida** [SpaceNetChallenge/utilities#11]
when I run :
aws s3api get-object --bucket spacenet-dataset --key AOI_1_Rio/srcData/rasterData/8-Band.tar.gz --request-payer requester 8-Band.tar.gz

I get the following error:
An error occurred (AccessDenied) when calling the GetObject operation: Access Denied

For the other files, I did not such download problem.

**Comment by dlindenbaum** [comment]
Hello,

Thank you for working with SpaceNet
Please try again.  I checked the ACLs and it was wrong.  

It's been switched to public-read.

Thank you,

**Comment by smajida** [comment]
@dlindenbaum 
thanks. The problem is solved.

**Comment by adwin5** [comment]
@smajida @dlindenbaum 
is the dataset still available now?
I have the access denied error
Thanks

**Comment by dlindenbaum** [comment]
@adwin5 It should be available.  No changes to access have occurred recently.  What commands are you using to access the dataset?

Thank you,
David

**Comment by adwin5** [comment]
@dlindenbaum 
I configured regions name to us-east-1,
output format GeoTIFF
and use the command same as above
aws s3api get-object --bucket spacenet-dataset --key AOI_1_Rio/srcData/rasterData/8-Band.tar.gz --request-payer requester 8-Band.tar.gz

**Comment by dlindenbaum** [comment]
@adwin5 I've checked the acls- for the dataset.  It exists and downloads.  

in addition to us-east-1 do you have a valid aws Access Key ID and Secret Access Key?  

Thank you,
Dave
