### ISSUE TITLE
Dataset for height of all objects

### ISSUE THREAD

**Issue by rohun-tripathi** [SpaceNetChallenge/utilities#111]
Hi,
I am exploring the SpaceNet dataset. I am interested in ground truth labels for heights of objects off of the ground. Do we have ground truth labels for that in the dataset?
Thanks!

**Comment by nrweir** [comment]
Hi Rohun,

Unfortunately those labels don't exist for the SpaceNet Challenge Datasets. However, the Urban 3D challenge dataset hosted by SpaceNet does provide these labels for the associated imagery: https://spacenetchallenge.github.io/datasets/Urban_3D_Challenge_summary.html

Good luck!
