### ISSUE TITLE
COCO annotations?

### ISSUE THREAD

**Issue by ash1995** [SpaceNetChallenge/utilities#113]
Currently it is possible to utilise spacenet utilities to convert spacenet annotations to Pascal VOC/Darknet annotation formats. Are there any plans to introduce a functionality that will allow us to convert annotations into the MS COCO format?

**Comment by nrweir** [comment]
Hi ash1995,

Great question. As we re-structure our entire software stack these are the types of things we're considering. Given the high prevalence of models that use COCO-formatted labels, I expect that is something we'll end up incorporating, but can't say for sure.
