### ISSUE TITLE
Why was the latlon2pixel function removed from geoTools.py in spacenetutilitiesV3?

### ISSUE THREAD

**Issue by ash1995** [SpaceNetChallenge/utilities#114]
As far as I can tell, the only difference between the geoTools.py from the original spacenetutilities branch and the V3 branch is the removal of this function. I was just wondering why was this removed.

**Comment by nrweir** [comment]
Hi ash1995,

We're in the process of re-structuring this entire package, including changing functions from specific versions (e.g. latlon2pixel) to versions that can accommodate other formats (in this case, other coordinate reference systems).
