### ISSUE TITLE
Off Nadir Dataset query: Images taken at different nadir angles have same annotation 

### ISSUE THREAD

**Issue by ash1995** [SpaceNetChallenge/utilities#115]
Hi,

I have a doubt regarding the SpaceNet Off Nadir dataset. The images in the dataset are named according to the following criteria: 'Atlanta_nadir{nadir-angle}_catid_{catid}_{x}_{y}'. The dataset contains 1064 geojson files which contain the building locations as labels. 

Shouldn't the number of labels/geojson files be equal to the number of images in the dataset? If not, how do I resolve the following problem:

Here image 1 and image 2 are of the same location as exemplified by the UTM x and y coordinates in their names but are taken at two different angles (13 and 53 respectively). However, the geojson that corresponds to this name (image 3) doesn't match the image at high nadir angles (53 in this case). This would actually hurt the model while training as it would be forcing it to learn the wrong representation. How would I go about resolving this issue? 

1. **Pan-Sharpen_Atlanta_nadir13_catid_1030010002B7D800_742151_3741339**
![atlanta_nadir13_catid_1030010002b7d800_742151_3741339](https://user-images.githubusercontent.com/32295036/52909650-8c848b00-32a5-11e9-8791-7f3ab6c316a4.jpg)

2. **Pan-Sharpen_Atlanta_nadir53_catid_1030010003CD4300_742151_3741339**
![atlanta_nadir53_catid_1030010003cd4300_742151_3741339](https://user-images.githubusercontent.com/32295036/52909652-8d1d2180-32a5-11e9-8ccb-673011df6e29.jpg)

3. **spacenet-building_742151_3741339.geojson**
![spacenet-building_742151_3741339](https://user-images.githubusercontent.com/32295036/52909736-bc805e00-32a6-11e9-9377-611cd7c1392a.png)

**Comment by nrweir** [comment]
Hi ash1995,

In short, the building footprints label _where the buildings sit on the ground_ from a geospatial standpoint. This doesn't change as the look angle changes, though the distortion/displacement of the building and roof may make it appear that way. It is indeed harder to relate the building footprint to the image as the look angle increases - that's a big part of what this dataset is meant to show.

Depending upon what your goal is, the model may not be learning the "wrong" thing from these labels. If your goal is to place building footprints on the ground in a geospatially accurate manner, even from images with bad look angles, then it will need to learn how to address distortions. If your goal is just to find the roof of the building in the image, then indeed that might not be too useful (that said, we would argue that finding the geospatially displaced roof of a building isn't particularly useful for real world applications).
