### ISSUE TITLE
Scene metadata for Off-Nadir dataset

### ISSUE THREAD

**Issue by maptopixel** [SpaceNetChallenge/utilities#116]
The scene metadata (IMD XML file) was made available for the previous spacenet releases (https://github.com/SpaceNetChallenge/utilities/issues/60). This is very useful. 

Are there any plans to do the same for the off-nadir data?

**Comment by nrweir** [comment]
Hi maptopixel,

I believe the data you need is up on the S3 bucket: check out the `workorder_[ID number]_01.xml` files in `s3://spacenet-dataset/AOI_6_Atlanta/[collect subdirs]`.

I'm going to close the issue, feel free to reopen if you have trouble finding it!

-Nick
