### ISSUE TITLE
error while running creatDataSpaceNet.py

### ISSUE THREAD

**Issue by oneOfThePeople** [SpaceNetChallenge/utilities#16]
hi
i run this line in python 
`createDataSpaceNet.py ~/spacenet-data/AOI_5_Khartoum_Train/`
and the code exit like this (in the terminal)- 
`Segmentation fault (core dumped)
`
and like this in pycharm -
`Process finished with exit code 139 (interrupted by signal 11: SIGSEGV) 
`
 when  i do debugging i see that the problrm acure in this line at labelTools.py
`gdal.RasterizeLayer(target_ds, [1], innerBufferLayer, burn_values=[100])
`
you saw somthing like this before?
thank

**Comment by dlindenbaum** [comment]
Hello,

That's interesting,  I have not seen that error.  
I just ran the code against AOI_5_Khartoum_Train to check and did not get the error.  

Does the error occur on the first image it tries to process or is it after several images?  If it's not the first image can you see if the error occurs on the same image every time? 

Thank you,  

Dave

**Comment by oneOfThePeople** [comment]
The error occur on the first image.
So i take random image (img 50), run the code and its work
Maybe the download was wrong and there is damage images
I will check and update
Thank you

**Comment by oneOfThePeople** [comment]
I download the images again and i got same error...
in most of the image that i check the cod not working...

**Comment by dlindenbaum** [comment]
Hello, 
I re-downloaded the data, spun up a new docker container and ran it without issue.  Code has been tested in Ubuntu 16.04 and mac OSX
```
python createDataSpaceNet.py ~/spacenet-data/AOI_5_Khartoum_Train/

```
_________________________________________
I guess it's time to ask questions about your setup.
What OS?
What GDAL version is python using? 
in python execute
``` 
from osgeo import gdal
gdal.VersionInfo()

```

What gdal executables do you have
on command line?
```
gdalinfo --version

GDAL 1.11.3, released 2015/09/16

```

Thanks, 
Hopefully we can solve this.  

Dave

**Comment by oneOfThePeople** [comment]
ubuntu 16.04
python 2.7 
GDAL 2.1.3, released 2017/20/01
i try to install with pip GDAL 1.11.3 
` sudo -H  pip install GDAL==1.11.3`
the output is 
>  Could not find a version that satisfies the requirement GDAL==1.11.3 (from versions: 1.5.0, 1.5.2, 1.6.0, 1.6.1, 1.7.0, 1.7.1, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.11.0, 1.11.1, 1.11.2, 2.0.0, 2.0.1, 2.1.0, 2.1.3)
> No matching distribution found for GDAL==1.11.3
>

**Comment by oneOfThePeople** [comment]
ok the gdal was the problem 
thank you very mach

**Comment by dlindenbaum** [comment]
Great, Closing this Issue
