### ISSUE TITLE
Example code for converting from lat/log to x/y

### ISSUE THREAD

**Issue by aurotripathy** [SpaceNetChallenge/utilities#2]
I need help with converting geojson lat/log to x/y pixels. Is there a simple example? 

The helper function is available in getTools.py, what's missing is an example of how to put it together.

The example can take as input any tif file and its corresponding geojson file and return the pixel coordinates of the bounding-boxes.
 
Thank you.

**Comment by aurotripathy** [comment]
I got a small sample working, closing this out so as not to waste bandwidth on this.
```
from spaceNet import geoTools as gT
import numpy as np
from pudb import set_trace


if __name__ == "__main__":
    truth_fp = '../../data/AOI_1_Rio/processedData/vectorData/summaryData/AOI_1_Rio_polygons_solution_8Band.geojson'

    sol_polys = gT.importgeojson(truth_fp, removeNoBuildings=True)

    sol_polysIdsList = np.asarray([item['ImageId'] for item in sol_polys if item["ImageId"] > 0 and \
                                   item['BuildingId']!=-1])

    sol_polysBIdsList = np.asarray([item['BuildingId'] for item in sol_polys if item["ImageId"] > 0 and \
                                    item['BuildingId']!=-1])

    sol_polysPoly = np.asarray([item['poly'] for item in sol_polys if item["ImageId"] > 0 and \
                                item['BuildingId']!=-1])

for ids, bId, geom in zip(sol_polysIdsList, sol_polysBIdsList, sol_polysPoly):
    pts = geom.GetGeometryRef(0)
    print '--------{}----{}------'.format(ids, bId)
    for p in range(pts.GetPointCount()):
        print 'x {}, y {}'.format(pts.GetX(p), pts.GetY(p))

```

**Comment by dlindenbaum** [comment]
Hello,

Thank you for your interest.  Over the next few weeks we will be pushing out more code and examples.  All feedback is appreciated.  

Yes, the data is provided in both pixel and geo.  An example Can be seen in geoTools in the function 
geoPolygonToPixelPolygonWKT

You can look at https://pcjericks.github.io/py-gdalogr-cookbook/geometry.html as a good reference for how to create a geometry

Thank you,
Dave
