### ISSUE TITLE
evaluate buildings detection from spaceNet

### ISSUE THREAD

**Issue by yghlc** [SpaceNetChallenge/utilities#24]
Hello, 
   The codes provides scripts for result evaluation, just like following:
```
python python/evaluateScene.py /path/to/SpaceNetTruthFile.csv \
                               /path/to/SpaceNetProposalFile.csv \
                               --resultsOutputFile /path/to/SpaceNetResults.csv
```
I confuse how to evaluate because my alogrithm output is not a csv table, but a label image which while pixels belong to building and dark pixels belong to background.
I also can convert the label images to geojson files by using GDAL Polygonize function, but there are two issues:

1. how to assign the id for each building polygon? In the "SpaceNetTruthFile.csv", each building polygon has a building ID, how to make sure the building in my result has the same ID as in the "SpaceNetTruthFile.csv". At least, the correct detected building polygons should have correct ID.
2. For the case which two or more building are close to each other, the detected result shows they are connected to each other (see the bottom white area of below figure), the polygonized function will convert this white area to one polygon, but the truth is two separated polygons, this will make the IOU value small and consider the detected result is wrong. So how to deal this case?  I don't think it's wrong, just because they are too close.
![rgb-pansharpen_aoi_2_vegas_8bit_img4_blob_0 copy](https://cloud.githubusercontent.com/assets/10796190/25303314/9b579be8-2782-11e7-8538-4ce9a6e20443.png)

**Comment by dlindenbaum** [comment]
Hello,
It's great that you've been able to develop your algorithm.  Can I ask what algorithm you are using? 

In response.
1.  There is no need to match the buildingID from your proposal file to the truth file.  It is just a counter field.  It's main function it to indicate an empty tile by indicating -1.  The CSV submission format is for the SpaceNET Round 2 competition.  Currently going on at http://crowdsourcing.topcoder.com/spacenet.  I'd encourage you to compete.  

2.  For a detailed look at how the metric works, see in https://medium.com/the-downlinq/the-spacenet-metric-612183cc2ddb as it has a good walk through.  When using this metric which emphasizes individual building footprint extraction, It is considered wrong if the two buildings are merged together. 

Thank you,
Dave

**Comment by yghlc** [comment]
Thanks Dave!
  The algorithm I used is Deep Convolutional Nets. Currently, I am working on my final project of the deep learning course at CUHK. The report deadline final project is in 3 days, so I'm working heavily on that.
    I knew the competition two weeks ago when I tried to download spaceNet for my course project. A little late for the competition. I will continue working on that if I have time and try to upload my result.
