### ISSUE TITLE
error with SBD data

### ISSUE THREAD

**Issue by oneOfThePeople** [SpaceNetChallenge/utilities#29]
i try run the command
```
python python/createDataSpaceNet.py PATH/AOI_5_Khartoum_Train  
--srcImageryDirectory RGB-PanSharpen  
--outputDirectory PATH/AOI_5_Khartoum_Train/annotations 
 --annotationType SBD --outputFileType JPEG 

```
there is problem with line 118 in createDataSpaceNet.py because we send bboxresize to geoJsonToSBD function and the parmeter not exist there

**Comment by dlindenbaum** [comment]
@oneOfThePeople Hello,

Thanks for pointing out the error.  I'll work on getting that finished this week.

Thank you,

**Comment by oneOfThePeople** [comment]
Hi,
If you take the code from [here ](https://github.com/lncohn/pascal_to_spacenet_2) so its update now and should to work

**Comment by dlindenbaum** [comment]
@oneOfThePeople #31 
Error with code is fixed.
