### ISSUE TITLE
Building footprint data and its source

### ISSUE THREAD

**Issue by maptopixel** [SpaceNetChallenge/utilities#37]
What is the source of the ground-truth building footprints provided in the SpaceNet data on AWS? Is it data from by the relevant national map agency of each sample dataset? Or is it produced from some internal Digital Globe building database or manually digitised from the same imagery? What QA has been done on it? I'm most interested in the Shanghai AOI which is a WV-3 dataset.

**Comment by dlindenbaum** [comment]
Hello,
The Las Vegas, Paris, Shanghai and Khartoum AOI datasets were manually digitized from the same imagery for the purpose of the competition and QA/QCed in house through the process.

**Comment by maptopixel** [comment]
Thanks for the quick reply.
