### ISSUE TITLE
about data

### ISSUE THREAD

**Issue by qinhaifangpku** [SpaceNetChallenge/utilities#4]
hi~all
i have seen the spacenet challenge in http://crowdsourcing.topcoder.com/spacenet
but i wonder where i could get the data,  train data and test data?
and what should i post in the topcoder?

thank you for your help in advance!

**Comment by toddstavish** [comment]
Data can be found here:

https://aws.amazon.com/public-datasets/spacenet/

Submissions, implementations, metric are described here:

http://crowdsourcing.topcoder.com/spacenet_asset_library

**Comment by qinhaifangpku** [comment]
@toddstavish thank you! i have downloaded the data. and i still could not found the submissions describtion in the adress you provied.  could you give me a more clearly link adress?
in addition when i click the [object detcttion on spacenet]  in http://crowdsourcing.topcoder.com/spacenet_asset_library .  it cannot open.
thank you for your help in advance!

**Comment by toddstavish** [comment]
Here is a direct link to the object detection on spacenet post -

https://medium.com/the-downlinq/object-detection-on-spacenet-5e691961d257

The exact submission format (including a way to visualize your proposals)
will be released in the next couple of days on the TopCoder site.
