### ISSUE TITLE
Missing scene metadata / .imd files

### ISSUE THREAD

**Issue by maptopixel** [SpaceNetChallenge/utilities#60]
Hi,

I've been looking over the Spacenet data for Shanghai. The WV3 metadata doesn't appear to be included (the .IMD files). For my classification research I need to be able to calculate TOA radiance (and potentially reflectance) using the metadata file. Is it possible for the IMD files to be provided please?

Thanks

**Comment by dlindenbaum** [comment]
Hello,

That should be possible.  I have some of the IMD files right now but need to do some formatting.  I'll comment again with a location for the files.

What type of research are you doing?

Thank you,

**Comment by maptopixel** [comment]
Great. To be more specific it's for a PhD student's project who is investigating fusing Worldview-3 and Sentinel 2 and assessing the impact on built-up area classification accuracy . It's early stage but radiance calculation is the first step. Would be happy to provide more info as we go if it's of interest.

**Comment by maptopixel** [comment]
Hi there. I noticed the request for the metadata has been added to the next Utilities release. Do you know when this might be?

Thanks

**Comment by dlindenbaum** [comment]
Hello, 

I'm currently finishing that up right now with Utilities version 3 released by the end of the week.

However, the metadata is now uploaded to AWS.  

```
aws s3 ls s3://spacenet-dataset/AOI_4_Shanghai/srcData/rasterData/Shanghai_Imagery/ --request-payer requester

```
Thank you

**Comment by maptopixel** [comment]
Great, looks good. I did notice there appears to be a quickview image there which I don't think is of the same scene 16FEB29111913-M2AS-055649178040_01_P001-BROWSE.JPG. Not sure if you meant to include that in that dir.

 Thanks for sharing the metadata.
