### ISSUE TITLE
Unable to download dataset from aws

### ISSUE THREAD

**Issue by duplex143** [SpaceNetChallenge/utilities#79]
I'm unable to download most of the spacenet [datasets](https://spacenetchallenge.github.io/AOI_Lists/AOI_2_Vegas.html). For e.g., when I'm trying to download the Las Vegas Building Training Dataset using the command 
`aws s3api get-object --bucket spacenet-dataset --key AOI_2_Vegas/AOI_2_Vegas_Train.tar.gz --request-payer requester AOI_2_Vegas_Train.tar.gz`, it's downloading partially (~70%) and I'm getting the error `HTTPSConnectionPool(host='spacenet-dataset.s3.amazonaws.com', port=443): Read timed out.`. It's happening for most of the datasets. I've tried tweaking the parameters as mentioned [here](http://docs.aws.amazon.com/cli/latest/topic/s3-config.html) but with no use. Kindly guide me.

**Comment by dlindenbaum** [comment]
Hello,

I am not sure how to help you.  It looks like you are having trouble downloading the large files.   This isn't something that we've had reporter before.  What type of data connection are you working on?

Thank you,

**Comment by duplex143** [comment]
Apparently, this has something to do with my ssh server in which I was trying to download. Downloading is fine in Google Cloud though. I still haven't figured out the problem with my server.
