### ISSUE TITLE
An error occurred (AccessDenied) when calling the GetObject operation: Access Denied

### ISSUE THREAD

**Issue by moeedkundi** [SpaceNetChallenge/utilities#80]
I've been trying to download pre-trained models of a listed solution of road detection challenge i.e. by selim_sef.  Following is the script given on this git repository:

```
mkdir trained_models
aws s3 sync s3://spacenet-dataset/SpaceNet_Roads_Competition/Pretrained_Models/04-selim_sef/ trained_models/
```

which results in 
> An error occurred (AccessDenied) when calling the GetObject operation: Access Denied

then i ran the following code to check the files present in this folder at aws:
```
aws s3 ls s3://spacenet-dataset/SpaceNet_Roads_Competition/Pretrained_Models/04-selim_sef/
```
and it successfully showed all files.

But when i tried to download a single file using this command:
```
aws s3api get-object --bucket spacenet-dataset --key SpaceNet_Roads_Competition/Pretrained_Models/04-selim_sef/000_paris_linknet_inception.h5 --request-payer requester 000_paris_linknet_inception.h5
```
 it still gives me the same error.

**Comment by dlindenbaum** [comment]
Hello,

I reviewed it and there was an error in the permissions on that group of files.  Please try again.  It should be fixed.

Thank you,
