### ISSUE TITLE
createDataSpaceNet.py doesn't convert all objects in geojson to bounding boxes for Darknet

### ISSUE THREAD

**Issue by reachsumit** [SpaceNetChallenge/utilities#81]
I am trying to generate Darknet style bounding boxes for spacenet tif files. The .gejson file for the corresponding tif files has more than 15 buildings. However, the createDataSpaceNet.py always outputs one entry in the text file. No error is given in the terminal.

**Comment by ash1995** [comment]
@reachsumit I'm facing a similar problem while working with the Spacenet Off Nadir dataset. Converting annotations to Darknet format results in only a few annotations being converted and those that are converted are empty files. Were you able to successfully convert your annotations to Darknet annotations?

**Comment by reachsumit** [comment]
@ash1995 IIRC, it didn't work for me. So, I used this: https://medium.com/the-downlinq/getting-started-with-spacenet-data-827fd2ec9f53 with a bit of customization.
