### ISSUE TITLE
Permissions on the spacenet AWS S3 bucket

### ISSUE THREAD

**Issue by nseeburn** [SpaceNetChallenge/utilities#83]
I'm having trouble accessing data from the SpaceNet AWS public dataset. From previous similar issues there might be a permissions issue on the spacenet bucket.

I've verified that my access keyid, secret access key and region are configured correctly and was able to successfully list one of the LandSat open dataset buckets at s3://landsat-pds

I've attached the list command I use:
`aws s3 ls s3://spacenet-dataset/ --request-payer requester`

And the error message that is returned:
`An error occurred (AccessDenied) when calling the ListObjects operation: Access Denied`

**Comment by dlindenbaum** [comment]
Hello,

Thank you for trying to access the SpaceNet dataset.  No permissions should have changed recently with the dataset.  

I just created a new account and verified that

```aws s3 ls s3://spacenet-dataset/ ``` works with it.  

One thing to try.  SpaceNet is no longer a requester-pays bucket  therefor can you try it with out the request-payer tag?  

Otherwise it may be a more complex problem.

Thank you

**Comment by nseeburn** [comment]
Thank you very much for getting back to me, I really appreciate it, especially as you must get this a lot. Just tried it without the request-payer tag, no luck. In the case that the bucket isn't requester-pays, from my understanding (which I'm happy to be wrong about) I think wget-ing the repo might also work, but returns a 430 error for me.

**Comment by dlindenbaum** [comment]
Hello,

Thanks for the log file.  The log file looks correct.  The only thing I can see is that your aws-cli is a couple of generations old at this point.  However I don't think that should effect capability.

Dave

**Comment by nseeburn** [comment]
I've just succeeded with my own personal instance. Looks like an issue on this end I wasn't aware of. I will proceed to interrogate an admin. Sorry to have bothered you, and thanks again for your help!

**Comment by dlindenbaum** [comment]
Great,  I'm going to close the issue.  If you have any additional information that could help others and can provide it please do.
