### ISSUE TITLE
Is the Challenge dataset open to use for other purposes?

### ISSUE THREAD

**Issue by AnarBonny** [SpaceNetChallenge/utilities#84]
Hi, I missed the Challenge deadline. Is any of the Challenge datasets allowed to be used in computer vision research? Thank you

**Comment by dlindenbaum** [comment]
Hello,

Yes, the dataset is designed to be able to be used for continued computer vision research. The SpaceNet Buildings, Buildings V2 and Roads Dataset by SpaceNet Partners is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License. 

For more information about how to access the various datasets please see the below link.

https://spacenetchallenge.github.io/datasets/datasetHomePage.html

The other remote sensing datasets may have slightly different licenses but all licenses support it's use for computer vision research as long as long as the citing requirements are followed.

What type of research are you looking to perform?
