### ISSUE TITLE
Cannot access public dataset SPACENET 

### ISSUE THREAD

**Issue by tayalkshitij** [SpaceNetChallenge/utilities#86]
On `http://spacenet-dataset.s3.amazonaws.com/` , public s3 bucket is `arn:aws:s3:::spacenet-dataset.`
However when I try to access the bucket via https
`http://spacenet-dataset.s3.amazonaws.com/`, it is giving following error 
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>80AA03A4A2B74B07</RequestId>
<HostId>
vpeLzorRhAVQAc5WIy7aC9atGuyrgnBw+xdRR8GklvasUI4jgQ+Bd8Yl6Jo9QU5rQnbcMOkwxME=
</HostId>
</Error>
```

Is this dataset no longer public ?

**Comment by dlindenbaum** [comment]
Hello,

The dataset is public.  However it requires an aws account to access.

It can be accessed through the aws command line tool or through presigned links.

https://spacenetchallenge.github.io/ has instructions for ways to access the data sets 

Thank you,
Dave

**Comment by antran89** [comment]
Hi @tayalkshitij 
We need to configure aws-cli first with your key and secret, and use aws-cli to access to the S3 bucket.
```
aws configure
```
