### ISSUE TITLE
 AOI_2_Vegas_Train.tar.gz can not be rightly unzipped

### ISSUE THREAD

**Issue by tianyu0523** [SpaceNetChallenge/utilities#90]
When I unzip the file  AOI_2_Vegas_Train.tar.gz, I meet a problem. I use ubuntu command "tar zxvf AOI_2_Vegas_Train.tar.gz". It shows the error information as below
"gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
"

**Comment by dlindenbaum** [comment]
Hello,

This usually means that the file did not download completely or that you have run out of space locally.

How large is the tarball?

Thank you

**Comment by nrweir** [comment]
Closing since this hasn't seen traffic in a month - if this issue gets encountered again feel free to comment and we can re-open.
