### ISSUE TITLE
error on running createDataSpaceNet.py

### ISSUE THREAD

**Issue by LiliMeng** [SpaceNetChallenge/utilities#91]
File "/Users/lilimeng/Desktop/Price_prediction/SpaceNet/utilities/python/spaceNetUtilities/labelTools.py", line 4, in <module>
    import geoTools as gT
ImportError: No module named 'geoTools'

**Comment by nrweir** [comment]
Hi LiliMeng,

Can you provide us a little bit more information about the environment where this occurred? For example:
- Did you `pip install` the spacenetutilities package?
- Which version of `spacenetutilities` are you using (master, v2, or v3)?

**Comment by nrweir** [comment]
As mentioned above, this is an issue that we're going to fix for 4.0.0. Going to mark this as a duplicate for clarity, even though you were the first to mention it (thanks for that!)
