### ISSUE TITLE
Implement continuous integration

### ISSUE THREAD

**Issue by nrweir** [SpaceNetChallenge/utilities#96]
# Implement continuous integration

At one point in the past we had CircleCI set up for this repository. @dlindenbaum, do you know what the status on that was?

Ideally we should get this up and running again for at least python 2.7 and 3.6 with the versions of dependencies we want (see the related issue) with testing (see #95). We should probably also automatically trigger for PRs.

@dlindenbaum let me know if you want to take this one, or I can have a shot at figuring out how to do it.

**Comment by dlindenbaum** [comment]
I can work this.  We've moved to travis.ci.

It integrated well with pytest.  I can build the backbone and use it for measuring progress for 

#95

**Comment by dlindenbaum** [comment]
Initial testing framework is done for python 3.6

**Comment by nrweir** [comment]
Resolved with #102
